In [ ]:
import pandas as pd

In [ ]:
iris_df = pd.read_csv("iris.csv")

In [ ]:
iris_df.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

### Iris Dataset Features

- **sepal_length** - Length of the flower's sepal.
- **sepal_width** - Width of the flower's sepal.
- **petal_length** - Length of the flower's peetal.
- **petal_width** - Width of the flower's petal.
- **species** - Species of the Iris flower.

In [ ]:
tips_df = pd.read_csv("tips.csv")

In [ ]:
tips_df.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

### Tips Dataset Features

- **total_bill** - Total amount of the restaurant bill.
- **tip** - Amount of the tip.
- **sex** - Sex category of the customer.
- **smoker** - Indicates whether the customer was a smoker.
- **day** - Day of the week.
- **time** - Time of the meal, such as lunch or dinner.
- **size** - Number of people in the dining group.

In [ ]:
flights_df = pd.read_csv("flights.csv")

In [ ]:
flights_df.head(10)

   year      month  passengers
0  1949    January         112
1  1949   February         118
2  1949      March         132
3  1949      April         129
4  1949        May         121
5  1949       June         135
6  1949       July         148
7  1949     August         148
8  1949  September         136
9  1949    October         119

### Flights Dataset Features

- **year** - Year of the flight data.
- **month** - Month of the flight data.
- **passengers** - Number of airline passengers.

In [ ]:
sales_df = pd.read_excel("sample_pivot.xlsx")

In [ ]:
sales_df.head(10)

        Date Region                 Type  Units  Sales
0 2020-07-11   East  Children's Clothing   18.0    306
1 2020-09-23  North  Children's Clothing   14.0    448
2 2020-04-02  South     Women's Clothing   17.0    425
3 2020-02-28   East  Children's Clothing   26.0    832
4 2020-03-19   West     Women's Clothing    3.0     33
5 2020-02-05  North     Women's Clothing   33.0    627
6 2020-01-24  South     Women's Clothing   12.0    396
7 2020-03-25   East     Women's Clothing   29.0    609
8 2020-01-03  North  Children's Clothing   18.0    486
9 2020-11-03   East  Children's Clothing   34.0    374

### Sales Dataset Features

- **Date** - Date of the sales record.
- **Region** - Region where the sale occurred.
- **Type** - Type of clothing sold.
- **Units** - Number of units sold.
- **Sales** - Sales amount.

In [ ]:
scores_df = pd.read_excel("Scores.xlsx")

In [ ]:
scores_df.head(10)

     English    History
0  74.573424  86.496775
1  75.115299  86.801171
2  75.691345  87.981466
3  73.888714  85.411392
4  75.015225  86.812830
5  75.185700  87.271474
6  75.108740  86.433501
7  74.802044  87.097021
8  73.799699  85.802903
9  75.982909  88.532761

### Scores Dataset Features

- **English** - English subject score.
- **History** - History subject score.

In [14]:
weather_df = pd.read_excel("toronto-weather.xlsx")

In [15]:
weather_df.head(10)

,STATION_NAME,LOCAL_DATE,MEAN_TEMPERATURE,MIN_TEMPERATURE,MAX_TEMPERATURE
0,TORONTO CITY CENTRE,2020-01-01,0.5,-0.8,1.7
1,TORONTO CITY CENTRE,2020-01-02,3.3,1.6,4.9
2,TORONTO CITY CENTRE,2020-01-03,5.1,3.0,7.2
3,TORONTO CITY CENTRE,2020-01-04,2.1,0.3,3.9
4,TORONTO CITY CENTRE,2020-01-05,0.4,-0.9,1.7
5,TORONTO CITY CENTRE,2020-01-06,1.2,-0.7,3.0
6,TORONTO CITY CENTRE,2020-01-07,0.2,-3.5,3.8
7,TORONTO CITY CENTRE,2020-01-08,-3.4,-7.5,0.8
8,TORONTO CITY CENTRE,2020-01-09,-3.4,-9.5,2.7
9,TORONTO CITY CENTRE,2020-01-10,4.2,2.3,6.0

### Toronto Weather Dataset Features

- **STATION_NAME** - Name of the weather station.
- **LOCAL_DATE** - Date of the weather observation.
- **MEAN_TEMPERATURE** - Average temperature for the day.
- **MIN_TEMPERATURE** - Lowest temperature for the day.
- **MAX_TEMPERATURE** - Highest temperature for the day.

In [16]:
anscombe_df = pd.read_json("anscombe.json")

In [17]:
anscombe_df.head(10)

  Series   X      Y
0      I  10   8.04
1      I   8   6.95
2      I  13   7.58
3      I   9   8.81
4      I  11   8.33
5      I  14   9.96
6      I   6   7.24
7      I   4   4.26
8      I  12  10.84
9      I   7   4.81

### Anscombe Dataset Features

- **Series** - Identifies the dataset group.
- **X** - X value for the observation.
- **Y** - Y value for the observation.

In [18]:
barley_df = pd.read_json("barley.json")

In [19]:
barley_df.head(10)

      yield    variety  year             site
0  27.00000  Manchuria  1931  University Farm
1  48.86667  Manchuria  1931           Waseca
2  27.43334  Manchuria  1931           Morris
3  39.93333  Manchuria  1931        Crookston
4  32.96667  Manchuria  1931     Grand Rapids
5  28.96667  Manchuria  1931           Duluth
6  43.06666    Glabron  1931  University Farm
7  55.20000    Glabron  1931           Waseca
8  28.76667    Glabron  1931           Morris
9  38.13333    Glabron  1931        Crookston

### Barley Dataset Features

- **yield** - Amount of barley produced.
- **variety** - Variety of barley.
- **year** - Year of the observation.
- **site** - Location where the barley was grown.

In [20]:
burtin_df = pd.read_json("burtin.json")

In [21]:
burtin_df.head(10)

,Bacteria,Penicillin,Streptomycin,Neomycin,Gram_Staining,Genus
0,Aerobacter aerogenes,870.000,1.00,1.600,negative,other
1,Bacillus anthracis,0.001,0.01,0.007,positive,other
2,Brucella abortus,1.000,2.00,0.020,negative,other
3,Diplococcus pneumoniae,0.005,11.00,10.000,positive,other
4,Escherichia coli,100.000,0.40,0.100,negative,other
5,Klebsiella pneumoniae,850.000,1.20,1.000,negative,other
6,Mycobacterium tuberculosis,800.000,5.00,2.000,negative,other
7,Proteus vulgaris,3.000,0.10,0.100,negative,other
8,Pseudomonas aeruginosa,850.000,2.00,0.400,negative,other
9,Salmonella (Eberthella) typhosa,1.000,0.40,0.008,negative,Salmonella

### Burtin Dataset Features

- **Bacteria** - Name of the bacterial species.
- **Penicillin** - Measurement of penicillin effectiveness.
- **Streptomycin** - Measurement of streptomycin effectiveness.
- **Neomycin** - Measurement of neomycin effectiveness.
- **Gram_Staining** - Gram-staining classification of the bacteria.
- **Genus** - Genus of the bacteria.